name: CI
on: 
  push

jobs:

  x86-64_test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Build Intel
      run: |
        arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        arch -x86_64 python -c "import platform; print(platform.uname())" 
        arch -x86_64 python -m pip install -r requirements.txt
        /usr/local/bin/brew install libomp
        arch -x86_64 conan profile detect --name build_x86
        arch -x86_64 conan create . -pr:h build_x86 -pr:b build_x86
      shell: bash
    - uses: actions/upload-artifact@v4
      with:
        name: x86_64_artifact
        path: ~/build_x86_64

  arm64_test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11' 
    - name: Build Arm
      run: | 
        /usr/bin/arch -arm64 /bin/zsh --login
        python --version
        python -c "import platform; print(platform.uname())" 
        python -m pip install -r requirements.txt
        /opt/homebrew/bin/brew install libomp
        conan profile detect --name build_arm
        conan create . -pr:h build_arm -pr:b build_arm
      shell: bash
    - uses: actions/upload-artifact@v4
      with:
        name: arm64_artifact
        path: ~/build_arm64

  fat_binary:
    needs: [x86-64_test, arm64_test]
    runs-on: macos-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        path: cross_artifacts
    - name: Display structure of downloaded files
      run: ls -R cross_artifacts   
    run: |
      lipo -create cross_artifacts/arm64_artifact/bin/cross cross_artifacts/x86_64_artifact/bin/cross -output fat/cross
    - uses: actions/upload-artifact@v4
      with:
        name: fat_artifact
        path: fat/cross