name: CI
on: push

jobs:
  test1:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11' 
    - run: arch -x86_64 python --version
    - run: arch -x86_64 python -c "import platform; print(platform.uname())" 
    - run: arch -x86_64 python -m pip install -r requirements.txt
    - run: arch -x86_64 brew install libomp
    - run: arch -x86_64 conan profile detect --name build_x86
    - run: arch -x86_64 conan build . -pr:h build_x86 -pr:b build_x86

  test2:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11' 
    - run: arch -arm64 python --version
    - run: arch -arm64 python -c "import platform; print(platform.uname())" 
    - run: arch -arm64 python -m pip install -r requirements.txt
    - run: arch -arm64 brew install libomp
    - run: arch -arm64 conan profile detect --name build_arm
    - run: arch -arm64 conan build . -pr:h build_arm -pr:b buil_arm

