name: CI
on: push

jobs:

  test1:
    runs-on: macos-latest
    steps:
    - run: arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Build Intel
      run: |
        arch -x86_64 python --version
        arch -x86_64 python -c "import platform; print(platform.uname())" 
        arch -x86_64 python -m pip install -r requirements.txt
        eval "$(/usr/local/bin/brew shellenv)"
        arch -x86_64 brew install libomp
        arch -x86_64 conan profile detect --name build_x86
#        export OpenMP_ROOT=$(arch -x86_64 brew --prefix)/opt/libomp
        arch -x86_64 conan build . -pr:h build_x86 -pr:b build_x86
      shell: bash

  test2:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11' 
    - name: Build Arm
      run: | 
        arch -arm64 python --version
        arch -arm64 python -c "import platform; print(platform.uname())" 
        arch -arm64 python -m pip install -r requirements.txt
        export PATH="/usr/local/bin:$PATH"
        arch -arm64 /opt/homebrew/bin/brew install libomp
        arch -arm64 conan profile detect --name build_arm
        arch -arm64 conan build . -pr:h build_arm -pr:b build_arm
      shell: bash

