name: CI
on: push

jobs:
  test1:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10' 
        architecture: 'x64'
        cache: pip
    - run: python --version
    - run: python -c "import platform; print(platform.uname())" 
    - run: pip install -r requirements
    - run: conan profile detect

  test2:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11' 
        architecture: 'arm64'
        cache: pip
    - run: python --version
    - run: python -c "import platform; print(platform.uname())"
    - run: pip install -r requirements
    - run: conan profile detect

