name: CI
on: push

jobs:
  test1:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11' 
    - run: arch -x86_64 python --version
    - run: arch -x86_64 python -c "import platform; print(platform.uname())" 
    - run: arch -x86_64 python -m pip install -r requirements.txt
    - run: arch -x86_64 conan profile detect -f

  test2:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11' 
    - run: arch -arm64 python --version
    - run: arch -arm64 python -c "import platform; print(platform.uname())" 
    - run: arch -arm64 python -m pip install -r requirements.txt
    - run: arch -arm64 conan profile detect -f

