name: CI
on: 
  push

jobs:

  x86-64_test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Build Intel
      run: |
        arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        arch -x86_64 python -c "import platform; print(platform.uname())" 
        arch -x86_64 python -m pip install -r requirements.txt
        /usr/local/bin/brew install libomp
        arch -x86_64 conan profile detect --name build_x86
        arch -x86_64 conan create . -pr:h build_x86 -pr:b build_x86
      shell: bash
    - uses: actions/upload-artifact@v4
      with:
        name: x86_64_artifact
        path: ~/BundleTest

  arm64_test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11' 
    - name: Build Arm
      run: | 
        /usr/bin/arch -arm64 /bin/zsh --login
        python --version
        python -c "import platform; print(platform.uname())" 
        python -m pip install -r requirements.txt
        /opt/homebrew/bin/brew install libomp
        conan profile detect --name build_arm
        conan create . -pr:h build_arm -pr:b build_arm
      shell: bash
    - uses: actions/upload-artifact@v4
      with:
        name: arm64_artifact
        path: ~/BundleTest


  fat_build:
    runs-on: macos-latest
    steps: 
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11' 
    - name: Brew libomp to fat 
      run: | 
        /usr/bin/arch -arm64 /bin/zsh --login
        python --version
        python -c "import platform; print(platform.uname())" 
        python -m pip install -r requirements.txt
        # Install libomp armv8
        /opt/homebrew/bin/brew install libomp  
        export libomp_arm=$(readlink -f  $(brew --prefix libomp))  
        cp -r $libomp_arm ~/libomp 
        rm ~/libomp/lib/*.*
        # Install libomp x86_64
        arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        arch -x86_64 python -m pip install -r requirements.txt
        /usr/local/bin/brew install libomp
        export libomp_x86_64=$(readlink -f  $(/usr/local/bin/brew --prefix libomp))
        # Merge the binaries
        lipo -create $libomp_arm/lib/libomp.dylib $libomp_x86_64/lib/libomp.dylib -output ~/libomp/lib/libomp.dylib
        lipo -create $libomp_arm/lib/libomp.a $libomp_x86_64/lib/libomp.a -output ~/libomp/lib/libomp.a
        # Fix the LC_ID_DYLIB to support correct loading in the bundle (see http://clarkkromenaker.com/post/library-dynamic-loading-mac/)
        install_name_tool -id @loader_path/../Frameworks/libomp.dylib ~/libomp/lib/libomp.dylib
    - uses: actions/upload-artifact@v4
      with:
        name: libomp_fat_artifact
        path: ~/libomp
    - name: Build Universal binary
      run: |
        conan profile detect --name build_arm
        conan create . -pr:h build_arm -pr:b build_arm -s="arch=armv8|x86_64"
        echo "THIS_PACKAGE==$(echo $HOME/build_arm)" >> $GITHUB_ENV


    - uses: actions/upload-artifact@v4
      with:
        name: fat_package_artifact
        path: ~/BundleTest

